# Generated by Django 4.2.17 on 2024-12-17 04:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trusteddevice',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('75ca1ec2-e2a1-4e97-b3f0-a7f9cdb9d31f'), unique=True),
        ),
    ]
