# Generated by Django 4.2.17 on 2024-12-17 04:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_trusteddevice_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trusteddevice',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('b3d3572e-073c-4525-9d2f-a017c72d5020'), unique=True),
        ),
    ]
