# Generated by Django 4.2.17 on 2024-12-17 06:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_trusteddevice_device_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginattempt',
            old_name='was_successfutl',
            new_name='was_successful',
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('44a1ce34-5c9e-4a7d-b8ea-eab54e1d7484'), unique=True),
        ),
    ]
