# Generated by Django 4.2.17 on 2024-12-18 04:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_was_successfutl_loginattempt_was_successful_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('172f53ba-0d95-4ff0-b326-0245eaa5aefa'), unique=True),
        ),
    ]
