# Generated by Django 4.2.17 on 2024-12-19 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_trusteddevice_device_id_authenticationsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trusteddevice',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('4166f3b0-4d9c-47f0-8c6c-47a6a5b44bdf'), unique=True),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.UUID('caf288ac-b49d-4db5-83a2-8a46de5eb733'), editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
