# Generated by Django 4.2.17 on 2024-12-19 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_trusteddevice_device_id_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='token',
            field=models.UUIDField(default=uuid.UUID('ba9bea9a-aec1-4846-b643-1091a764869a'), editable=False),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('cfe0155b-edf8-471b-8b36-541973eab083'), unique=True),
        ),
    ]
