# Generated by Django 4.2.17 on 2024-12-20 00:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_emailverification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='token',
            field=models.UUIDField(default=uuid.UUID('92304358-d68a-4c3c-b442-dc75edb565e2'), editable=False),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('8bdc05c1-4ecb-42e4-8ffd-d929ba073ef3'), unique=True),
        ),
    ]
