# Generated by Django 4.2.17 on 2024-12-20 00:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_emailverification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='token',
            field=models.UUIDField(default=uuid.UUID('ff236a73-5a6a-4af9-ab8c-cb705002bb2f'), editable=False),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('ddcffcb6-9d51-43b3-919d-e34cc867d025'), unique=True),
        ),
    ]
