# Generated by Django 4.2.17 on 2024-12-20 01:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_emailverification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='token',
            field=models.UUIDField(default=uuid.UUID('098a7612-e919-4f4b-975d-3ff0a3c55c56'), editable=False),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('ab9c41a0-ec91-4ac8-8c82-a518f39bb306'), unique=True),
        ),
    ]
