# Generated by Django 4.2.17 on 2024-12-20 04:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_emailverification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='token',
            field=models.UUIDField(default=uuid.UUID('e85c81b3-fdb8-4dba-8295-87b43bec1b64'), editable=False),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('23edb1af-1482-4931-a18a-cfd9a4f0b581'), unique=True),
        ),
    ]
