# Generated by Django 5.1.4 on 2024-12-20 19:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_emailverification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='token',
            field=models.UUIDField(default=uuid.UUID('af40ffab-3dfa-49f7-ba57-65e63a9afd1e'), editable=False),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('a36227f1-59e3-4ec6-b694-01ce3b9738db'), unique=True),
        ),
    ]
