# Generated by Django 5.1.4 on 2024-12-20 20:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_emailverification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='token',
            field=models.UUIDField(default=uuid.UUID('99d85df2-b4dd-4a1a-97ce-10794937c724'), editable=False),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('988fecf7-63b8-4b20-86fd-6b0691d30590'), unique=True),
        ),
    ]
