# Generated by Django 4.2.17 on 2024-12-20 22:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_emailverification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='token',
            field=models.UUIDField(default=uuid.UUID('bc489e35-46ae-4ab2-b865-59082a5dfcef'), editable=False),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('5865248d-a7d4-4215-8468-fd1d92b17459'), unique=True),
        ),
    ]
