# Generated by Django 4.2.17 on 2024-12-20 22:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_emailverification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='token',
            field=models.UUIDField(default=uuid.UUID('45a4f37a-9f37-4561-9c35-b4d3f1e0b1a0'), editable=False),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('75db5011-6590-42e5-8cee-1eed8b28f196'), unique=True),
        ),
    ]
